server.port=8124

spring.application.name=studentCRUD


spring.datasource.url=jdbc:mysql://localhost:3306/Jpastudent
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
